### ISSUE TITLE
biopython dependency not picked up correctly at install

### ISSUE THREAD

**Issue by s-andrews** [asntech/pyjaspar#2]
Trying to install pyjaspar on a fresh python install fails because despite biopython being listed as a dependency the installation fails because of a lack of this package.  It might be linked to not having wheel installed as well?

```
C:\Users\andrewss\Desktop\JASPAR> pip install pyjaspar
Defaulting to user installation because normal site-packages is not writeable
Collecting pyjaspar
  Downloading pyjaspar-2.1.0.tar.gz (43.7 MB)
     |████████████████████████████████| 43.7 MB 6.8 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\andrewss\\AppData\\Local\\Temp\\pip-install-8p1y4xzp\\pyjaspar_0fdc9f535cbb4133be9ff175177fe563\\setup.py'"'"'; __file__='"'"'C:\\Users\\andrewss\\AppData\\Local\\Temp\\pip-install-8p1y4xzp\\pyjaspar_0fdc9f535cbb4133be9ff175177fe563\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\andrewss\AppData\Local\Temp\pip-pip-egg-info-yi1_f8ww'
         cwd: C:\Users\andrewss\AppData\Local\Temp\pip-install-8p1y4xzp\pyjaspar_0fdc9f535cbb4133be9ff175177fe563\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\andrewss\AppData\Local\Temp\pip-install-8p1y4xzp\pyjaspar_0fdc9f535cbb4133be9ff175177fe563\setup.py", line 15, in <module>
        from pyjaspar import __version__ as VERSION
      File "C:\Users\andrewss\AppData\Local\Temp\pip-install-8p1y4xzp\pyjaspar_0fdc9f535cbb4133be9ff175177fe563\pyjaspar\__init__.py", line 49, in <module>
        from Bio import BiopythonWarning
    ModuleNotFoundError: No module named 'Bio'
    ----------------------------------------
```

If you manually install biopython first then it works:

```
C:\Users\andrewss\Desktop\JASPAR> pip install biopython
Defaulting to user installation because normal site-packages is not writeable
Collecting biopython
  Downloading biopython-1.79-cp39-cp39-win_amd64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB ...
Collecting numpy
  Downloading numpy-1.22.3-cp39-cp39-win_amd64.whl (14.7 MB)
     |████████████████████████████████| 14.7 MB ...
Installing collected packages: numpy, biopython
Successfully installed biopython-1.79 numpy-1.22.3

C:\Users\andrewss\Desktop\JASPAR> pip install pyjaspar
Defaulting to user installation because normal site-packages is not writeable
Collecting pyjaspar
  Using cached pyjaspar-2.1.0.tar.gz (43.7 MB)
Requirement already satisfied: biopython in c:\users\andrewss\appdata\roaming\python\python39\site-packages (from pyjaspar) (1.79)
Requirement already satisfied: numpy in c:\users\andrewss\appdata\roaming\python\python39\site-packages (from biopython->pyjaspar) (1.22.3)
Using legacy 'setup.py install' for pyjaspar, since package 'wheel' is not installed.
Installing collected packages: pyjaspar
    Running setup.py install for pyjaspar ... done
Successfully installed pyjaspar-2.1.0

```

**Comment by asntech** [comment]
Thanks @s-andrews for reporting this! It appears this is because the `wheel` dependency is not listed - as you pointed. Since `wheel` req is listed in biopython- it worked. I will add `wheel` or feel free to make a pull-request. Thanks!
